export enum ActionTypes {
    TEST = 'TEST',
    TEST2 = 'TEST2',
    ADD_NOTE = 'ADD_NOTE',
    UPDATE_NOTE = 'UPDATE_NOTE',
    GET_MANUFACTURERS = 'GET_MANUFACTURERS',
    EXPAND_CONFIG_GROUP = 'EXPAND_CONFIG_GROUP',
    SELECT_CONFIG = 'SELECT_CONFIG'
}