export enum ActionTypes {
    TEST = 'TEST',
    TEST2 = 'TEST2',
    ADD_NOTE = 'ADD_NOTE',
    UPDATE_NOTE = 'UPDATE_NOTE',

    GET_MANUFACTURERS = 'GET_MANUFACTURERS',
    EXPAND_CONFIG_GROUP = 'EXPAND_CONFIG_GROUP',
    SELECT_CONFIG = 'SELECT_CONFIG',
    TOGGLE_PROPERTY_INHERITANCE = 'TOGGLE_PROPERTY_INHERITANCE',
    CHANGE_PROPERTY_VALUE = 'CHANGE_PROPERTY_VALUE',
    SAVE_PROPERTY_OPTIONS = 'SAVE_PROPERTY_OPTIONS',
    LOAD_ORGANIZATIONS = 'LOAD_ORGANIZATIONS',
    CHANGE_ORGANIZATION = 'CHANGE_ORGANIZATION',

    GET_FIRMWARE_FILES = 'GET_FIRMWARE_FILES',
    ADD_FIRMWARE_FILE = 'ADD_FIRMWARE_FILE',
    DELETE_FIRMWARE_FILE = 'DELETE_FIRMWARE_FILE'
}